version: 2
project_name: wt

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: wt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/glennr/wt/cmd.Version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore"
      - "^ci"
      - "^docs"

release:
  github:
    owner: glennr
    name: wt
